#!/usr/bin/env bash

source "${app_common}"

app::use 'error'
app::use 'site'

main() {
    while [[ $# -gt 0 ]]; do
        case "${1}" in
            -- ) shift && break ;;
            -* ) app::error::unknown_option "${1}" ;;
            * ) break
        esac

        shift
    done

    if [[ $# -gt 1 ]]; then
        app::error::too_many_arguments 1
    fi

    if [[ $# -lt 1 ]]; then
        app::error::missing_argument 'path to site or config file'
    fi

    local site_path="${1}"

    local -A site_config=()

    app::site::load_site_config "${site_path}"

    app_header 'Plugin'

    echo "Name: ${site_config[plugin]##*/}"
    echo "Path: ${site_config[plugin_path]:-~}"

    app_header 'Site'

    local local_config_file="${site_config[local_config_file]:-~}"

    echo "Main config:  ${site_config[base_config_file]:-~}"
    echo "Local config: ${local_config_file##*/}"
    echo
    echo "Root:    ${site_config[root]:-~}"
    echo "Exclude: ${site_config[exclude]:-~}"
    echo "Include: ${site_config[include]:-~}"

    app_header 'Database'

    echo "Name:     ${site_config[database_name]:-~}"
    echo "User:     ${site_config[database_user]:-~}"
    echo "Password: ${site_config[database_password]:-~}"
}

app_header() {
    printf "\n### %s\n\n" "${1}"
}

main "$@"
