#!/usr/bin/env bash

source "${app_common}"

app::use 'error'
app::use 'plugin'

main() {
    local opt_all=false

    while [[ $# -gt 0 ]]; do
        case "${1}" in
            -a | --all ) opt_all=true ;;
            -- ) shift && break ;;
            -* ) app::error::unknown_option "${1}" ;;
            * ) break
        esac

        shift
    done

    if [[ $# -gt 0 ]]; then
        app::error::too_many_arguments 0
    fi

    if [[ "${opt_all}" == 'true' ]]; then
        app::plugin::plugins_list
    else
        app::plugin::plugins_list | xargs -n1 basename | sort -u
    fi
}

main "$@"
