#!/usr/bin/env bash

source "${app_common}"

app::use 'database'
app::use 'error'
app::use 'site'

main() {
    local opt_help=false

    while [[ $# -gt 0 ]]; do
        case "${1}" in
            -h | --help ) opt_help=true ;;
            -- ) shift && break ;;
            -?* ) app::error::unknown_option "${1}" ;;
            * ) break
        esac

        shift
    done

    if [[ "${opt_help}" == 'true' ]]; then
        app_help

        exit 0
    fi

    if [[ $# -gt 2 ]]; then
        app::error::too_many_arguments 2
    fi

    if [[ $# -lt 1 ]]; then
        app::error::missing_argument 'path to site or config file'
    fi

    if [[ $# -lt 2 ]]; then
        app::error::missing_argument 'path to backup file'
    fi

    if ! [[ -f "${2}" && -r "${2}" ]]; then
        app::error::error "Backup file not exists or not readable: ${2}"
    fi

    local site_path="${1}"
    local backup_file="$(realpath "${2}")"

    app_restore_site_files

    local -A site_config=(
        [backup_file]="${backup_file}"
    )

    app::site::load_site_config "${site_path}"

    printf 'Site: %s\n' "${site_config[root]}"
    printf 'Plugin: %s\n' "${site_config[plugin]}"

    app_restore_site_database

    printf 'Done: %s\n' "${site_config[root]}"
}

app_restore_site_files() {
    local -A site_config=()

    app::site::load_main_config "${site_path}" 'main'

    if [[ "${site_path}" == '-' || "${site_path}" == '/dev/stdin' ]]; then
        site_path="${site_config[root]}"
    fi

    if ! [[ -d "${site_config[root]}" ]]; then
        app::error::error "Site path not exists or not a directory: ${site_config[root]}"
    fi

    if ! [[ -z "$(command ls -A ${site_config[root]})" ]]; then
        app::error::error "Site path is not empty: ${site_config[root]}"
    fi

    if ! [[ -w "${site_config[root]}" ]]; then
        app::error::error "Site path is not writable: ${site_config[root]}"
    fi

    echo 'Processing... This may take a while.'

    command unzip -qd "${site_config[root]}" "${backup_file}"
}

app_restore_site_database() {
    local site_path="${site_config[root]}"
    local dump_file_suffix="${site_config[database_dump_suffix]}"

    local -a dump_files=("${site_path}/"*"${dump_file_suffix}")

    [[ "${#dump_files[@]}" -eq 0 ]] && return

    if [[ "${#dump_files[@]}" -gt 1 ]]; then
        app::error::error "Multiple database dump files found: ${dump_files[*]}"
    fi

    dump="$(realpath "${dump_files[0]}")"

    read -r -p "Database dump found: ${dump##*/}. Load? [y/n] "

    [[ "${REPLY}" != 'y' ]] && return

    app::database::cli < "${dump}"

    command rm --force "${dump}"
}

app_help() {
    local app_command="${0##*/}"

    cat <<HELP
Restore site

Usage:

  ${app_name} ${app_command} [options] <site path> <backup file>

Arguments:

  site path    Path to site's root or config file
  backup file  Path to backup file (.zip)

Options:

  -h, --help  Show this help
HELP
}

main "$@"
