#!/usr/bin/env bash

set -eu -o pipefail -o noglob
shopt -s lastpipe nullglob

source "${app_libs_path}/error.bash"
source "${app_libs_path}/info.bash"
source "${app_libs_path}/plugin.bash"
source "${app_libs_path}/site.bash"
source "${app_libs_path}/util.bash"
source "${app_base_path}/utils.bash"

main() {
    local verbose=false

    while [ $# -gt 0 ]; do
        case "${1}" in
            -v | --verbose ) verbose=true ;;
            -- ) shift && break ;;
            -* ) app:error:unknown_option "${1}" ;;
            * ) break
        esac

        shift
    done

    if [ $# -gt 2 ]; then
        app:error:too_many_arguments 2
    fi

    if [ $# -lt 1 ]; then
        app:error:missing_argument 'path to site'
    fi

    if [ $# -lt 2 ]; then
        app:error:missing_argument 'path to backup file'
    fi

    local site_path="$(realpath $1)"
    local backup_file="$(realpath $2)"

    app::site::check_site_path_exists_and_readable "${site_path}"

    if [ -f "${backup_file}" ]; then
        app:error:error "Backup file already exists: ${backup_file}"
    fi

    local -A site_config=()

    app::site::detect_site_config "${site_path}" 'site_config'

    app::info::plugin   'site_config'
    app::info::site     'site_config'
    app::info::database 'site_config'
    app::info::backup

    printf '\nProcessing... This may take a while.\n'

    cd "${site_path}"

    if [[ -z "${site_config[exclude_paths]:-}${site_config[include_paths]:-}" ]]; then
        app_zip -u "${backup_file}" .
    else
        if [[ -n "${site_config[include_paths]:-}" ]]; then
            app_zip -u "${backup_file}" . -i ${site_config[include_paths]}
        fi

        if [[ -n "${site_config[exclude_paths]:-}" ]]; then
            app_zip -u "${backup_file}" . -x ${site_config[exclude_paths]}
        fi
    fi

    if [[ -z "${site_config[database_name]:-}" ]]; then
        app::info::result

        exit 0
    fi

    local dump="$(mktemp --suffix ${app_database_dump_file_suffix})"

    app_dump_database > "${dump}" \
        && app_zip -ju "${backup_file}" "${dump}"

    rm --force "${dump}"

    app::info::result
}

main "$@"
