#!/usr/bin/env bash

set -eu -o pipefail
shopt -s lastpipe nullglob

source "${app_libs_loader}"

app::use 'error'
app::use 'database'
app::use 'site'

main() {
    while [[ $# -gt 0 ]]; do
        case "${1}" in
            -- ) shift && break ;;
            -* ) app::error::unknown_option "${1}" ;;
            * ) break
        esac

        shift
    done

    if [[ $# -gt 1 ]]; then
        app::error::too_many_arguments 1
    fi

    if [[ $# -lt 1 ]]; then
        app::error::missing_argument 'path to site'
    fi

    local site_path="$(realpath "${1}")"

    app::site::check_site_path_exists_and_readable "${site_path}"

    local -A site_config

    app::site::detect_config "${site_path}"

    if [[ -z "${site_config[database_name]:-}" ]]; then
        app::error::error 'Database not detected'
    fi

    app::database::cli
}

main "$@"
