#!/usr/bin/env bash

set -eu -o pipefail -o noglob
shopt -s lastpipe

source "${app_base_path}/utils.bash"

main() {
    while [ $# -gt 0 ]; do
        case "${1}" in
            -- ) shift && break ;;
            -* ) app_error_unknown_option "${1}" ;;
            * ) break
        esac

        shift
    done

    if [ $# -gt 1 ]; then
        app_error_too_many_arguments 1
    fi

    if [ $# -lt 1 ]; then
        app_error_missing_argument 'path to site'
    fi

    local site_path="$(realpath ${1})"

    app_check_site_path_exists_and_readable "${site_path}"

    cd "${site_path}"

    local -A site_config

    app_detect_site_config 'site_config'

    app_header_plugin 'site_config'
    app_header_paths 'site_config'
    app_header_database 'site_config' --show-password
}

main "$@"
