#!/usr/bin/env bash

set -eu -o pipefail
shopt -s lastpipe nullglob

source "${app_libs_path}/error.bash"
source "${app_libs_path}/plugin.bash"
source "${app_base_path}/utils.bash"

main() {
    while [[ $# -gt 0 ]]; do
        case "${1}" in
            -- ) shift && break ;;
            -* ) app:error:unknown_option "${1}" ;;
            * ) break
        esac

        shift
    done

    if [[ $# -gt 1 ]]; then
        app:error:too_many_arguments 1
    fi

    if [[ $# -lt 1 ]]; then
        app:error:missing_argument 'path to site'
    fi

    local site_path="$(realpath "${1}")"

    app_check_site_path_exists_and_readable "${site_path}"

    cd "${site_path}"

    local -A site_config

    app_detect_site_config 'site_config'

    app_header_plugin 'site_config'
    app_header_paths 'site_config'
    app_header_database 'site_config' --show-password
}

main "$@"
