#!/usr/bin/env bash

set -eu -o pipefail
shopt -s lastpipe nullglob

source "${app_libs_loader}"

app::use 'error'
app::use 'site'
app::use 'info'

main() {
    while [[ $# -gt 0 ]]; do
        case "${1}" in
            -- ) shift && break ;;
            -* ) app::error::unknown_option "${1}" ;;
            * ) break
        esac

        shift
    done

    if [[ $# -gt 1 ]]; then
        app::error::too_many_arguments 1
    fi

    if [[ $# -lt 1 ]]; then
        app::error::missing_argument 'path to site'
    fi

    local site_path="$(realpath "${1}")"

    app::site::check_site_path_exists_and_readable "${site_path}"

    local -A site_config=()

    app::site::detect_site_config "${site_path}"

    app::info::plugin   'site_config'
    app::info::site     'site_config'
    app::info::database 'site_config' --show-password
}

main "$@"
