#!/usr/bin/env bash

set -eu -o pipefail
shopt -s lastpipe nullglob

source "${app_libs_loader}"

app::use 'command'
app::use 'util'

main() {
    cat <<HELP
${app_name}: simple backup tool for web sites (Joomla, Wordpress & etc.).

$(app::util::usage '<command> [opts]')

$(app::command::available_commands)
HELP
}

main "$@"
