#!/usr/bin/env bash

set -eu -o pipefail
shopt -s lastpipe nullglob

source "${app_libs_loader}"

app::use 'error'
app::use 'plugin'

main() {
    while [[ $# -gt 0 ]]; do
        case "${1}" in
            -- ) shift && break ;;
            -* ) app::error::unknown_option "${1}" ;;
            * ) break
        esac

        shift
    done

    if [[ $# -gt 0 ]]; then
        app::error::too_many_arguments 0
    fi

    app::plugin::plugins_list | command xargs -n1 basename
}

main "$@"
