#!/usr/bin/env bash

set -eu -o pipefail
shopt -s lastpipe nullglob

source "${app_libs_path}/error.bash"
source "${app_base_path}/utils.bash"

main() {
    while [[ $# -gt 0 ]]; do
        case "${1}" in
            -- ) shift && break ;;
            -* ) app:error:unknown_option "${1}" ;;
            * ) break
        esac

        shift
    done

    if [[ $# -gt 0 ]]; then
        app:error:too_many_arguments 0
    fi

    app_plugins_list | xargs -n1 basename | sort
}

main "$@"
