#!/usr/bin/env bash

[ -f 'wp-config.php' ] || exit 1

cat <<CONFIG
plugin_name: WordPress
exclude: /wp-content/cache/*
CONFIG

sed -nE \
    -e "s/^.*DB_NAME.*'(.*)'.*$/database_name: \1/p" \
    -e "s/^.*DB_USER.*'(.*)'.*$/database_user: \1/p" \
    -e "s/^.*DB_PASSWORD.*'(.*)'.*$/database_password: \1/p" \
    'wp-config.php'
