#!/usr/bin/env bash

grep 'JConfig' 'configuration.php' &>/dev/null || exit 1

cat <<CONFIG
exclude: /cache/* /tmp/* /administrator/cache/*
include: */index.html
CONFIG

sed -nE \
    -e "s/^.*\\\$db[=[:space:]]+.*'(.*)'.*$/database_name: \1/p" \
    -e "s/^.*\\\$user[=[:space:]]+.*'(.*)'.*$/database_user: \1/p" \
    -e "s/^.*\\\$password[=[:space:]]+.*'(.*)'.*$/database_password: \1/p" \
    'configuration.php'
